"use client";

/**
 * components/pm/ReferenceFileLibrary.tsx
 * -----------------------------------------------------------------------------
 * A project's Reference Files library — spec sheets, codes, notes, and PDF
 * reports auto-generated by the AI Plan Analyzer's "Add to Project" action
 * (see lib/reference-file-store.ts, components/AddToProjectModal.tsx). Files
 * with a `sourceAnalysisId` are tagged so it's clear they came from a saved
 * analysis rather than a manual upload.
 * -----------------------------------------------------------------------------
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, FileText, Loader2, Sparkles, Trash2, Upload } from "lucide-react";
import type { ReferenceFileMeta, ReferenceFilesListResponseBody, ReferenceFileResponseBody } from "@/lib/reference-file-types";

export default function ReferenceFileLibrary({ projectId }: { projectId: string }) {
  const [files, setFiles] = useState<ReferenceFileMeta[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [description, setDescription] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const fetchFiles = useCallback(async () => {
    setError(null);
    try {
      const res = await fetch(`/api/projects/${projectId}/reference-files`);
      const payload = (await res.json()) as ReferenceFilesListResponseBody;
      if (!res.ok || !payload.success || !payload.files) {
        throw new Error(payload.error || "Failed to load reference files.");
      }
      setFiles(payload.files);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load reference files.");
      setFiles([]);
    }
  }, [projectId]);

  useEffect(() => {
    void fetchFiles();
  }, [fetchFiles]);

  async function handleFileChosen(file: File) {
    setUploading(true);
    setError(null);
    try {
      const fileBase64 = await fileToBase64(file);
      const res = await fetch(`/api/projects/${projectId}/reference-files`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fileName: file.name,
          mimeType: file.type || "application/octet-stream",
          description: description.trim() || undefined,
          fileBase64,
        }),
      });
      const payload = (await res.json()) as ReferenceFileResponseBody;
      if (!res.ok || !payload.success || !payload.file) {
        throw new Error(payload.error || "Upload failed.");
      }
      setFiles((prev) => [payload.file!, ...(prev ?? [])]);
      setDescription("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Upload failed.");
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }

  async function handleDelete(fileId: string) {
    setError(null);
    const prev = files;
    setFiles((cur) => (cur ? cur.filter((f) => f.id !== fileId) : cur));
    try {
      const res = await fetch(`/api/projects/${projectId}/reference-files/${fileId}`, { method: "DELETE" });
      const payload = (await res.json()) as { success: boolean; error?: string };
      if (!res.ok || !payload.success) throw new Error(payload.error || "Failed to delete file.");
    } catch (err) {
      setFiles(prev);
      setError(err instanceof Error ? err.message : "Failed to delete file.");
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-end sm:justify-between">
        <div className="flex flex-1 flex-col gap-1">
          <span className="text-xs font-medium text-slate-500">Description (optional)</span>
          <input
            type="text"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="e.g. Local building code excerpt, client spec sheet"
            className="rounded-md border border-slate-200 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-1 focus:ring-indigo-400"
          />
        </div>
        <div>
          <input
            ref={fileInputRef}
            type="file"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) void handleFileChosen(file);
            }}
          />
          <button
            type="button"
            disabled={uploading}
            onClick={() => fileInputRef.current?.click()}
            className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white transition-colors hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
            Upload File
          </button>
        </div>
      </div>

      {error && (
        <div className="flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {files === null ? (
        <div className="flex items-center justify-center gap-2 py-10 text-sm text-slate-500">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading reference files...
        </div>
      ) : files.length === 0 ? (
        <div className="flex flex-col items-center gap-2 rounded-2xl border border-dashed border-slate-200 bg-white p-10 text-center">
          <FileText className="h-8 w-8 text-slate-300" />
          <p className="text-sm font-medium text-slate-700">No reference files yet</p>
          <p className="text-xs text-slate-500">
            Upload spec sheets, codes, or notes — or run a Plan Analysis and use &quot;Add to Project&quot; to save a
            report here automatically.
          </p>
        </div>
      ) : (
        <div className="flex flex-col gap-2">
          {files.map((f) => (
            <div
              key={f.id}
              className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3"
            >
              <div className="flex min-w-0 items-center gap-3">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500">
                  <FileText className="h-4 w-4" />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-1.5">
                    <a
                      href={`/api/projects/${projectId}/reference-files/${f.id}`}
                      target="_blank"
                      rel="noreferrer"
                      className="truncate text-sm font-medium text-indigo-700 hover:underline"
                      title={f.fileName}
                    >
                      {f.fileName}
                    </a>
                    {f.sourceAnalysisId && (
                      <span className="flex shrink-0 items-center gap-1 rounded-full bg-indigo-50 px-1.5 py-0.5 text-[10px] font-medium text-indigo-600">
                        <Sparkles className="h-2.5 w-2.5" />
                        From analysis
                      </span>
                    )}
                  </div>
                  <p className="truncate text-xs text-slate-500">
                    {formatBytes(f.fileSize)} · {new Date(f.createdAt).toLocaleDateString()}
                    {f.description ? ` · ${f.description}` : ""}
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => handleDelete(f.id)}
                className="shrink-0 rounded-md p-1.5 text-slate-400 transition hover:bg-red-50 hover:text-red-600"
                aria-label={`Delete ${f.fileName}`}
                title="Delete"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.substring(result.indexOf(",") + 1));
    };
    reader.onerror = () => reject(reader.error ?? new Error("Failed to read file."));
    reader.readAsDataURL(file);
  });
}
